#!/bin/bash
# Local deployment guide - Run these commands manually

echo "==================================="
echo "Credit Reconciler Deployment Guide"
echo "==================================="
echo ""
echo "This script shows the commands to deploy the Credit Reconciler."
echo "Run each command manually to ensure proper AWS configuration."
echo ""

echo "1. First, ensure you have AWS credentials configured:"
echo "   aws sts get-caller-identity"
echo ""

echo "2. Create required secrets in AWS Secrets Manager:"
echo "   aws secretsmanager create-secret \\"
echo "     --name fertilia/openai \\"
echo "     --secret-string '{\"api_key\":\"your-openai-api-key\"}'"
echo ""

echo "3. Create SSM parameters for pricing:"
echo "   aws ssm put-parameter \\"
echo "     --name /fertilia/pricing/default \\"
echo "     --value \"0.10\" \\"
echo "     --type String"
echo ""
echo "   aws ssm put-parameter \\"
echo "     --name /fertilia/pricing/premium \\"
echo "     --value \"0.25\" \\"
echo "     --type String"
echo ""

echo "4. Build the SAM application:"
echo "   cd /Users/tdeshane/video-app/meta-agents/cc-agent-credit-reconciler"
echo "   sam build --use-container"
echo ""

echo "5. Deploy to AWS (first time - interactive):"
echo "   sam deploy --guided"
echo ""
echo "   Suggested parameters:"
echo "   - Stack Name: cc-agent-reconciler-dev"
echo "   - AWS Region: us-east-1"
echo "   - Parameter Environment: dev"
echo "   - Confirm changes before deploy: Y"
echo "   - Allow SAM CLI IAM role creation: Y"
echo "   - Save parameters to samconfig.toml: Y"
echo ""

echo "6. For subsequent deployments:"
echo "   sam deploy"
echo ""

echo "7. Run smoke tests:"
echo "   python scripts/smoke-test.py --env dev"
echo ""

echo "8. Check CloudWatch logs:"
echo "   aws logs tail /aws/lambda/cc-agent-reconciler-dev --follow"
echo ""

echo "==================================="
echo "Troubleshooting:"
echo "==================================="
echo ""
echo "If deployment fails:"
echo "1. Check CloudFormation console for error details"
echo "2. Ensure Docker is running for sam build"
echo "3. Verify AWS permissions for all required services"
echo ""

echo "To delete the stack:"
echo "   sam delete --stack-name cc-agent-reconciler-dev"