AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Credit Reconciler Agent - Keeps user credit ledger aligned with video generation work

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage
  TableSuffix:
    Type: String
    Default: dev
    Description: Suffix for DynamoDB table names
  BusName:
    Type: String
    Default: default
    Description: EventBridge bus name
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment (deprecated, use Stage)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: credit-reconciler
        LOG_LEVEL: INFO

Resources:
  # Lambda Function
  ReconcilerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub cc-agent-reconciler-${Stage}
      CodeUri: src/
      Handler: handler.lambda_handler
      ReservedConcurrentExecutions: 10
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt ReconcilerDLQ.Arn
      Layers:
        - !Ref SharedLayer
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          CREDITS_TABLE: !Ref CreditsTable
          LEDGER_TABLE: !Ref LedgerTable
          LLM_MODEL: gpt-4.1
          STAGE: !Ref Stage
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CreditsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref LedgerTable
        - CloudWatchPutMetricPolicy: {}
        - SSMParameterReadPolicy:
            ParameterName: fertilia/pricing/*
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:meta-agents/openai*'
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ReconcilerDLQ.Arn
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref OpsAlertsTopic
      Events:
        VideoRendered:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref BusName
            Pattern:
              source:
                - video.generation
              detail-type:
                - video.rendered
        VideoFailed:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref BusName
            Pattern:
              source:
                - video.generation
              detail-type:
                - video.failed
        ScheduledScan:
          Type: Schedule
          Properties:
            Schedule: rate(6 hours)
            Description: Catch-up scan for unreconciled jobs

  # DynamoDB Tables
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Jobs-${TableSuffix}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CreditsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Credits-${TableSuffix}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  LedgerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Ledger-${TableSuffix}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ledgerId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: ledgerId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: JobIdIndex
          KeySchema:
            - AttributeName: jobId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # EventBridge Event Bus (if using custom bus)
  VideoEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub video-events-${Stage}

  # Dead Letter Queue for failed events
  ReconcilerDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub cc-reconciler-dlq-${Stage}
      MessageRetentionPeriod: 1209600  # 14 days

  # Lambda Error Alarm
  ReconcilerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub cc-reconciler-errors-${Stage}
      AlarmDescription: Alert when reconciler Lambda has errors ≥1 in 5 min
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ReconcilerFunction
      AlarmActions:
        - !Ref OpsAlertsTopic
      TreatMissingData: notBreaching

  # Custom Metric Alarm
  AdjustmentRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub cc-reconciler-adjustments-${Stage}
      AlarmDescription: Alert on high adjustment rate
      MetricName: Adjustments
      Namespace: Reconciler
      Statistic: Sum
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold

  # Lambda Log Group
  ReconcilerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/cc-agent-reconciler-${Stage}
      RetentionInDays: 30

  # SNS Topic for operational alerts
  OpsAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ops-alerts-${Stage}
      DisplayName: !Sub "Operational Alerts - ${Stage}"

  # SNS Topic Policy
  OpsAlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowLambdaPublish
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sns:Publish
            Resource: !Ref OpsAlertsTopic
          - Sid: AllowCloudWatchPublish
            Effect: Allow
            Principal:
              Service: cloudwatch.amazonaws.com
            Action:
              - sns:Publish
            Resource: !Ref OpsAlertsTopic
      Topics:
        - !Ref OpsAlertsTopic

  # Shared Lambda Layer for secrets manager
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub meta-agents-shared-${Stage}
      ContentUri: ../shared/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

Outputs:
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ReconcilerFunction.Arn
  
  JobsTableName:
    Description: Jobs DynamoDB table name
    Value: !Ref JobsTable
  
  CreditsTableName:
    Description: Credits DynamoDB table name
    Value: !Ref CreditsTable
  
  LedgerTableName:
    Description: Ledger DynamoDB table name
    Value: !Ref LedgerTable
  
  DLQUrl:
    Description: Dead Letter Queue URL
    Value: !Ref ReconcilerDLQ
  
  OpsAlertsTopicArn:
    Description: SNS Topic ARN for operational alerts
    Value: !Ref OpsAlertsTopic