[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cc-agent-prompt-curator-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "cc-agent-prompt-curator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Environment=dev",
  "LLMModel=gpt-4"
]
